"""initial schema

Revision ID: 0001_initial_schema
Revises: none
Create Date: 2026-10-05 00:17:37.911979
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '0001_initial_schema'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Pin the baseline to the schema created by the current models. Shared native
# enums are created once before any table and removed only after all tables.
change_reason = postgresql.ENUM(
    'TRAINING_INGEST', 'USER_CORRECTION', 'MANUAL_EDIT', 'WORLD_EDIT',
    name='changereason', create_type=False,
)
source_type = postgresql.ENUM(
    'STORY', 'DIALOGUE', 'MANUAL_DESCRIPTION', 'WORLD_DERIVED',
    name='sourcetype', create_type=False,
)
world_source_type = postgresql.ENUM(
    'NOVEL_EPISODE', 'DESCRIPTION', name='worldsourcetype', create_type=False,
)
ingest_status = postgresql.ENUM(
    'PENDING', 'EXTRACTED', 'MERGED', 'FAILED',
    name='ingeststatus', create_type=False,
)
message_role = postgresql.ENUM(
    'USER', 'CHARACTER', name='messagerole', create_type=False,
)
native_enums = (
    change_reason, source_type, world_source_type, ingest_status, message_role,
)


def upgrade() -> None:
    if op.get_bind().dialect.name == 'postgresql':
        for enum_type in native_enums:
            enum_type.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('export_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('export_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_export_logs_user_id'), 'export_logs', ['user_id'], unique=False)
    op.create_table('import_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('import_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_logs_user_id'), 'import_logs', ['user_id'], unique=False)
    op.create_table('llm_usage',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('request_type', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('cached_input_tokens', sa.Integer(), nullable=False),
    sa.Column('reserved_total_tokens', sa.Integer(), nullable=False),
    sa.Column('budget_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost_usd', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('error_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_llm_usage_user_created', 'llm_usage', ['user_id', 'created_at'], unique=False)
    op.create_table('worlds',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worlds_user_id'), 'worlds', ['user_id'], unique=False)
    op.create_table('characters',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('world_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('profile_image_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_characters_user_id'), 'characters', ['user_id'], unique=False)
    op.create_index(op.f('ix_characters_world_id'), 'characters', ['world_id'], unique=False)
    op.create_table('world_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('world_id', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('world_id')
    )
    op.create_table('world_sources',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('world_id', sa.String(), nullable=False),
    sa.Column('source_type', world_source_type, nullable=False),
    sa.Column('series_name', sa.String(), nullable=True),
    sa.Column('episode_number', sa.Integer(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('extracted_data', sa.JSON(), nullable=True),
    sa.Column('status', ingest_status, nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_world_sources_world_id'), 'world_sources', ['world_id'], unique=False)
    op.create_table('character_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('character_id', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id')
    )
    op.create_table('conversations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('character_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_character_id'), 'conversations', ['character_id'], unique=False)
    op.create_table('correction_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('character_id', sa.String(), nullable=False),
    sa.Column('user_instruction', sa.Text(), nullable=False),
    sa.Column('resulting_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_correction_logs_character_id'), 'correction_logs', ['character_id'], unique=False)
    op.create_table('training_sources',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('character_id', sa.String(), nullable=False),
    sa.Column('source_type', source_type, nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('extracted_data', sa.JSON(), nullable=True),
    sa.Column('status', ingest_status, nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_sources_character_id'), 'training_sources', ['character_id'], unique=False)
    op.create_table('world_profile_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('world_profile_id', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('change_reason', change_reason, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['world_profile_id'], ['world_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_world_profile_history_world_profile_id'), 'world_profile_history', ['world_profile_id'], unique=False)
    op.create_table('character_profile_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('character_profile_id', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('change_reason', change_reason, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['character_profile_id'], ['character_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_character_profile_history_character_profile_id'), 'character_profile_history', ['character_profile_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('role', message_role, nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_correction_cmd', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_character_profile_history_character_profile_id'), table_name='character_profile_history')
    op.drop_table('character_profile_history')
    op.drop_index(op.f('ix_world_profile_history_world_profile_id'), table_name='world_profile_history')
    op.drop_table('world_profile_history')
    op.drop_index(op.f('ix_training_sources_character_id'), table_name='training_sources')
    op.drop_table('training_sources')
    op.drop_index(op.f('ix_correction_logs_character_id'), table_name='correction_logs')
    op.drop_table('correction_logs')
    op.drop_index(op.f('ix_conversations_character_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_table('character_profiles')
    op.drop_index(op.f('ix_world_sources_world_id'), table_name='world_sources')
    op.drop_table('world_sources')
    op.drop_table('world_profiles')
    op.drop_index(op.f('ix_characters_world_id'), table_name='characters')
    op.drop_index(op.f('ix_characters_user_id'), table_name='characters')
    op.drop_table('characters')
    op.drop_index(op.f('ix_worlds_user_id'), table_name='worlds')
    op.drop_table('worlds')
    op.drop_index('ix_llm_usage_user_created', table_name='llm_usage')
    op.drop_table('llm_usage')
    op.drop_index(op.f('ix_import_logs_user_id'), table_name='import_logs')
    op.drop_table('import_logs')
    op.drop_index(op.f('ix_export_logs_user_id'), table_name='export_logs')
    op.drop_table('export_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    if op.get_bind().dialect.name == 'postgresql':
        for enum_type in reversed(native_enums):
            enum_type.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
